#if !defined(AFX_AXISLABELSITEM1_H__6D95F1A2_375C_461A_9F0E_3BA4F23E8C1E__INCLUDED_)
#define AFX_AXISLABELSITEM1_H__6D95F1A2_375C_461A_9F0E_3BA4F23E8C1E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeFont;
class CGradient;
class CTeeRect;
class CTeeShadow;
class CPen1;
class CBackImage;

/////////////////////////////////////////////////////////////////////////////
// CAxisLabelsItem wrapper class

class CAxisLabelsItem : public COleDispatchDriver
{
public:
	CAxisLabelsItem() {}		// Calls COleDispatchDriver default constructor
	CAxisLabelsItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisLabelsItem(const CAxisLabelsItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	CTeeFont GetFont();
	CGradient GetGradient();
	long GetShadowSize();
	void SetShadowSize(long nNewValue);
	unsigned long GetShadowColor();
	void SetShadowColor(unsigned long newValue);
	BOOL GetTransparent();
	void SetTransparent(BOOL bNewValue);
	long GetShapeStyle();
	void SetShapeStyle(long nNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	CTeeRect GetShapeBounds();
	long GetBevel();
	void SetBevel(long nNewValue);
	long GetBevelWidth();
	void SetBevelWidth(long nNewValue);
	void ShowEditorShape();
	CTeeShadow GetShadow();
	long GetRoundSize();
	void SetRoundSize(long nNewValue);
	CPen1 GetPen();
	CBackImage GetPicture();
	void Show();
	void Hide();
	double GetValue();
	void SetValue(double newValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISLABELSITEM1_H__6D95F1A2_375C_461A_9F0E_3BA4F23E8C1E__INCLUDED_)
