#if !defined(AFX_FADERTOOL1_H__74C24B99_0886_49FA_92B5_885F72B54106__INCLUDED_)
#define AFX_FADERTOOL1_H__74C24B99_0886_49FA_92B5_885F72B54106__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CFaderTool wrapper class

class CFaderTool : public COleDispatchDriver
{
public:
	CFaderTool() {}		// Calls COleDispatchDriver default constructor
	CFaderTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFaderTool(const CFaderTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void Start();
	void Stop();
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetInitialDelay();
	void SetInitialDelay(long nNewValue);
	double GetSpeed();
	void SetSpeed(double newValue);
	long GetStyle();
	void SetStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FADERTOOL1_H__74C24B99_0886_49FA_92B5_885F72B54106__INCLUDED_)
