#if !defined(AFX_FIBONACCILEVELS_H__BDD1C84D_F5AC_4D81_A593_51529322D88A__INCLUDED_)
#define AFX_FIBONACCILEVELS_H__BDD1C84D_F5AC_4D81_A593_51529322D88A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CFibonacciItem;

/////////////////////////////////////////////////////////////////////////////
// CFibonacciLevels wrapper class

class CFibonacciLevels : public COleDispatchDriver
{
public:
	CFibonacciLevels() {}		// Calls COleDispatchDriver default constructor
	CFibonacciLevels(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFibonacciLevels(const CFibonacciLevels& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CFibonacciItem GetLevel(long Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FIBONACCILEVELS_H__BDD1C84D_F5AC_4D81_A593_51529322D88A__INCLUDED_)
