#if !defined(AFX_GAUGESERIES_H__FFFB1A5C_A51E_4045_952E_FA7DE11ACD18__INCLUDED_)
#define AFX_GAUGESERIES_H__FFFB1A5C_A51E_4045_952E_FA7DE11ACD18__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;
class CPointer;
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CGaugeSeries wrapper class

class CGaugeSeries : public COleDispatchDriver
{
public:
	CGaugeSeries() {}		// Calls COleDispatchDriver default constructor
	CGaugeSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGaugeSeries(const CGaugeSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetXRadius();
	void SetXRadius(long nNewValue);
	long GetYRadius();
	void SetYRadius(long nNewValue);
	long GetXCenter();
	long GetYCenter();
	long GetCircleWidth();
	long GetCircleHeight();
	unsigned long GetCircleBackColor();
	void SetCircleBackColor(unsigned long newValue);
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	long GetRotationAngle();
	void SetRotationAngle(long nNewValue);
	CTeePoint2D AngleToPoint(double Angle, double AXRadius, double AYRadius);
	double PointToAngle(long XCoord, long YCoord);
	double PointToRadius(long XCoord, long YCoord);
	CPointer GetCenter();
	CGradient GetCircleGradient();
	CPointer GetEndPoint();
	BOOL GetFullRepaint();
	void SetFullRepaint(BOOL bNewValue);
	double GetMaximum();
	void SetMaximum(double newValue);
	double GetMinimum();
	void SetMinimum(double newValue);
	long GetMinorTickDistance();
	void SetMinorTickDistance(long nNewValue);
	long GetHandDistance();
	void SetHandDistance(long nNewValue);
	long GetHandStyle();
	void SetHandStyle(long nNewValue);
	BOOL GetLabelsInside();
	void SetLabelsInside(BOOL bNewValue);
	double GetTotalAngle();
	void SetTotalAngle(double newValue);
	double GetValue();
	void SetValue(double newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GAUGESERIES_H__FFFB1A5C_A51E_4045_952E_FA7DE11ACD18__INCLUDED_)
