#if !defined(AFX_GIFEXPORT1_H__65FEEBCC_7394_4F09_AEEF_942FCB2A2EB1__INCLUDED_)
#define AFX_GIFEXPORT1_H__65FEEBCC_7394_4F09_AEEF_942FCB2A2EB1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGIFExport wrapper class

class CGIFExport : public COleDispatchDriver
{
public:
	CGIFExport() {}		// Calls COleDispatchDriver default constructor
	CGIFExport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGIFExport(const CGIFExport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	void SaveToFile(LPCTSTR FileName);
	VARIANT SaveToStream();
	long GetCompression();
	void SetCompression(long nNewValue);
	long GetDitherMode();
	void SetDitherMode(long nNewValue);
	long GetColorReduction();
	void SetColorReduction(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GIFEXPORT1_H__65FEEBCC_7394_4F09_AEEF_942FCB2A2EB1__INCLUDED_)
