#if !defined(AFX_GRAYSCALEFILTER_H__045292A4_ACA3_409E_AB49_78C19F8F1E1A__INCLUDED_)
#define AFX_GRAYSCALEFILTER_H__045292A4_ACA3_409E_AB49_78C19F8F1E1A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGrayScaleFilter wrapper class

class CGrayScaleFilter : public COleDispatchDriver
{
public:
	CGrayScaleFilter() {}		// Calls COleDispatchDriver default constructor
	CGrayScaleFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGrayScaleFilter(const CGrayScaleFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetMethod();
	void SetMethod(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRAYSCALEFILTER_H__045292A4_ACA3_409E_AB49_78C19F8F1E1A__INCLUDED_)
