// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gridtransposetool.h"


/////////////////////////////////////////////////////////////////////////////
// CGridTransposeTool properties

/////////////////////////////////////////////////////////////////////////////
// CGridTransposeTool operations

void CGridTransposeTool::Transpose()
{
	InvokeHelper(0x12d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

VARIANT CGridTransposeTool::GetSeries()
{
	VARIANT result;
	InvokeHelper(0x12e, DISPATCH_PROPERTYGET, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CGridTransposeTool::SetSeries(const VARIANT& newValue)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x12e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 &newValue);
}
