#if !defined(AFX_GRIDBANDBRUSH_H__7DC58F41_AA5E_4C25_B1E9_B76D2A950B3B__INCLUDED_)
#define AFX_GRIDBANDBRUSH_H__7DC58F41_AA5E_4C25_B1E9_B76D2A950B3B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGradient;

/////////////////////////////////////////////////////////////////////////////
// CGridBandBrush wrapper class

class CGridBandBrush : public COleDispatchDriver
{
public:
	CGridBandBrush() {}		// Calls COleDispatchDriver default constructor
	CGridBandBrush(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CGridBandBrush(const CGridBandBrush& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	void LoadImage(LPCTSTR FileName);
	void AssignImage(long ImageHandle);
	void ClearImage();
	void ShowEditor();
	long GetHandle();
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	long GetBrushLink();
	long GetTransparency();
	void SetTransparency(long nNewValue);
	CGradient GetGradient();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRIDBANDBRUSH_H__7DC58F41_AA5E_4C25_B1E9_B76D2A950B3B__INCLUDED_)
