#if !defined(AFX_HISTOGRAMFUNCTION1_H__9AED9270_3AFD_4283_89DE_4D6A2FC5504C__INCLUDED_)
#define AFX_HISTOGRAMFUNCTION1_H__9AED9270_3AFD_4283_89DE_4D6A2FC5504C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHistogramFunction wrapper class

class CHistogramFunction : public COleDispatchDriver
{
public:
	CHistogramFunction() {}		// Calls COleDispatchDriver default constructor
	CHistogramFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHistogramFunction(const CHistogramFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetCumulative();
	void SetCumulative(BOOL bNewValue);
	long GetNumBins();
	void SetNumBins(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HISTOGRAMFUNCTION1_H__9AED9270_3AFD_4283_89DE_4D6A2FC5504C__INCLUDED_)
