#if !defined(AFX_HISTOGRAMFUNCTION_H__7D1354FB_E2B8_4407_8840_E887F5B4EE74__INCLUDED_)
#define AFX_HISTOGRAMFUNCTION_H__7D1354FB_E2B8_4407_8840_E887F5B4EE74__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHistogramFunction wrapper class

class CHistogramFunction : public COleDispatchDriver
{
public:
	CHistogramFunction() {}		// Calls COleDispatchDriver default constructor
	CHistogramFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHistogramFunction(const CHistogramFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetCumulative();
	void SetCumulative(BOOL bNewValue);
	long GetNumBins();
	void SetNumBins(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HISTOGRAMFUNCTION_H__7D1354FB_E2B8_4407_8840_E887F5B4EE74__INCLUDED_)
