#if !defined(AFX_HORIZBOXPLOTSERIES_H__9D078DAB_6CFD_40AD_B9AC_54F1437FECCF__INCLUDED_)
#define AFX_HORIZBOXPLOTSERIES_H__9D078DAB_6CFD_40AD_B9AC_54F1437FECCF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPointer;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CHorizBoxPlotSeries wrapper class

class CHorizBoxPlotSeries : public COleDispatchDriver
{
public:
	CHorizBoxPlotSeries() {}		// Calls COleDispatchDriver default constructor
	CHorizBoxPlotSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHorizBoxPlotSeries(const CHorizBoxPlotSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CPointer GetPointer();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	long GetTransparency();
	void SetTransparency(long nNewValue);
	BOOL GetFastPoint();
	void SetFastPoint(BOOL bNewValue);
	long GetTreatNulls();
	void SetTreatNulls(long nNewValue);
	CPointer GetExtrOut();
	CPen1 GetMedianPen();
	CPointer GetMildOut();
	double GetPosition();
	void SetPosition(double newValue);
	double GetWhiskerLength();
	void SetWhiskerLength(double newValue);
	CPen1 GetWhiskerPen();
	CPointer GetBox();
	double GetMedian();
	void SetMedian(double newValue);
	double GetQuartile1();
	void SetQuartile1(double newValue);
	double GetQuartile3();
	void SetQuartile3(double newValue);
	double GetInnerFence1();
	void SetInnerFence1(double newValue);
	double GetInnerFence3();
	void SetInnerFence3(double newValue);
	double GetOuterFence1();
	void SetOuterFence1(double newValue);
	double GetOuterFence3();
	void SetOuterFence3(double newValue);
	double GetAdjacentPoint1();
	void SetAdjacentPoint1(double newValue);
	double GetAdjacentPoint3();
	void SetAdjacentPoint3(double newValue);
	BOOL GetUseCustomValues();
	void SetUseCustomValues(BOOL bNewValue);
	double MaxYValue();
	double MinYValue();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HORIZBOXPLOTSERIES_H__9D078DAB_6CFD_40AD_B9AC_54F1437FECCF__INCLUDED_)
