#if !defined(AFX_LINKTOOL_H__64BCAEE1_8C71_4439_90BC_23A074837986__INCLUDED_)
#define AFX_LINKTOOL_H__64BCAEE1_8C71_4439_90BC_23A074837986__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShapePanel;
class CAnnotationCallout;
class CBrush1;

/////////////////////////////////////////////////////////////////////////////
// CLinkTool wrapper class

class CLinkTool : public COleDispatchDriver
{
public:
	CLinkTool() {}		// Calls COleDispatchDriver default constructor
	CLinkTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLinkTool(const CLinkTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPosition();
	void SetPosition(long nNewValue);
	CTeeShapePanel GetShape();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	CAnnotationCallout GetCallout();
	long GetTextAlignment();
	void SetTextAlignment(long nNewValue);
	BOOL Clicked(long X, long Y);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	short GetCursor();
	void SetCursor(short nNewValue);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	BOOL GetAutoSize();
	void SetAutoSize(BOOL bNewValue);
	CBrush1 GetBrush();
	// method 'GetBounds' not emitted because of invalid return type or parameter type
	void SetBounds(long Left, long Top, long Right, long Bottom);
	long GetPositionUnits();
	void SetPositionUnits(long nNewValue);
	CString GetHint();
	void SetHint(LPCTSTR lpszNewValue);
	CString GetUrl();
	void SetUrl(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINKTOOL_H__64BCAEE1_8C71_4439_90BC_23A074837986__INCLUDED_)
