#if !defined(AFX_MACDFUNCTION_H__B6DB4D43_A052_4685_A4E7_9C57A0AD4362__INCLUDED_)
#define AFX_MACDFUNCTION_H__B6DB4D43_A052_4685_A4E7_9C57A0AD4362__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CSeries;

/////////////////////////////////////////////////////////////////////////////
// CMACDFunction wrapper class

class CMACDFunction : public COleDispatchDriver
{
public:
	CMACDFunction() {}		// Calls COleDispatchDriver default constructor
	CMACDFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CMACDFunction(const CMACDFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double GetPeriod2();
	void SetPeriod2(double newValue);
	CSeries GetMACDExp();
	CSeries GetHistogram();
	long GetPeriod3();
	void SetPeriod3(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MACDFUNCTION_H__B6DB4D43_A052_4685_A4E7_9C57A0AD4362__INCLUDED_)
