#if !defined(AFX_MODEFUNCTION1_H__EC772FAD_6113_43BE_9F14_F489C2F21E1B__INCLUDED_)
#define AFX_MODEFUNCTION1_H__EC772FAD_6113_43BE_9F14_F489C2F21E1B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CModeFunction wrapper class

class CModeFunction : public COleDispatchDriver
{
public:
	CModeFunction() {}		// Calls COleDispatchDriver default constructor
	CModeFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CModeFunction(const CModeFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetIncludeNulls();
	void SetIncludeNulls(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_MODEFUNCTION1_H__EC772FAD_6113_43BE_9F14_F489C2F21E1B__INCLUDED_)
