// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "performancefunction.h"


/////////////////////////////////////////////////////////////////////////////
// CPerformanceFunction properties

/////////////////////////////////////////////////////////////////////////////
// CPerformanceFunction operations

double CPerformanceFunction::Calculate(long SourceSeriesIndex, long FirstIndex, long LastIndex)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_R8, (void*)&result, parms,
		SourceSeriesIndex, FirstIndex, LastIndex);
	return result;
}
