#if !defined(AFX_PERFORMANCEFUNCTION1_H__B9732730_5C18_4482_B6F1_89B87CA02284__INCLUDED_)
#define AFX_PERFORMANCEFUNCTION1_H__B9732730_5C18_4482_B6F1_89B87CA02284__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPerformanceFunction wrapper class

class CPerformanceFunction : public COleDispatchDriver
{
public:
	CPerformanceFunction() {}		// Calls COleDispatchDriver default constructor
	CPerformanceFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPerformanceFunction(const CPerformanceFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	double Calculate(long SourceSeriesIndex, long FirstIndex, long LastIndex);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PERFORMANCEFUNCTION1_H__B9732730_5C18_4482_B6F1_89B87CA02284__INCLUDED_)
