#if !defined(AFX_PIESERIES_H__510CD770_32D7_463C_95AA_EFAD7187C783__INCLUDED_)
#define AFX_PIESERIES_H__510CD770_32D7_463C_95AA_EFAD7187C783__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint2D;
class CValueList;
class CPieOtherSlice;
class CExplodedSlices;
class CPen1;
class CTeeShadow;
class CGradient;
class CPieMarks;

/////////////////////////////////////////////////////////////////////////////
// CPieSeries wrapper class

class CPieSeries : public COleDispatchDriver
{
public:
	CPieSeries() {}		// Calls COleDispatchDriver default constructor
	CPieSeries(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPieSeries(const CPieSeries& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetXRadius();
	void SetXRadius(long nNewValue);
	long GetYRadius();
	void SetYRadius(long nNewValue);
	long GetXCenter();
	long GetYCenter();
	long GetCircleWidth();
	long GetCircleHeight();
	unsigned long GetCircleBackColor();
	void SetCircleBackColor(unsigned long newValue);
	BOOL GetCircled();
	void SetCircled(BOOL bNewValue);
	long GetRotationAngle();
	void SetRotationAngle(long nNewValue);
	CTeePoint2D AngleToPoint(double Angle, double AXRadius, double AYRadius);
	double PointToAngle(long XCoord, long YCoord);
	double PointToRadius(long XCoord, long YCoord);
	BOOL GetUsePatterns();
	void SetUsePatterns(BOOL bNewValue);
	CValueList GetPieValues();
	BOOL GetDark3D();
	void SetDark3D(BOOL bNewValue);
	long GetExplodeBiggest();
	void SetExplodeBiggest(long nNewValue);
	CPieOtherSlice GetOtherSlice();
	CExplodedSlices GetExplodedSlice();
	CPen1 GetPiePen();
	CTeeShadow GetShadow();
	long GetAngleSize();
	void SetAngleSize(long nNewValue);
	BOOL GetAutoMarkPosition();
	void SetAutoMarkPosition(BOOL bNewValue);
	CGradient GetGradient();
	long GetSliceHeight(long Index);
	void SetSliceHeight(long Index, long nNewValue);
	long GetDarkPen();
	void SetDarkPen(long nNewValue);
	long GetMultiPie();
	void SetMultiPie(long nNewValue);
	CPieMarks GetPieMarks();
	long GetGradientBright();
	void SetGradientBright(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PIESERIES_H__510CD770_32D7_463C_95AA_EFAD7187C783__INCLUDED_)
