#if !defined(AFX_RMSFUNCTION_H__E9BB9F93_D3BF_46FC_A864_AAE947D39283__INCLUDED_)
#define AFX_RMSFUNCTION_H__E9BB9F93_D3BF_46FC_A864_AAE947D39283__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMSFunction wrapper class

class CRMSFunction : public COleDispatchDriver
{
public:
	CRMSFunction() {}		// Calls COleDispatchDriver default constructor
	CRMSFunction(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMSFunction(const CRMSFunction& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetComplete();
	void SetComplete(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMSFUNCTION_H__E9BB9F93_D3BF_46FC_A864_AAE947D39283__INCLUDED_)
