// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "seriesgroups.h"

// Dispatch interfaces referenced by this interface
#include "seriesgroup.h"


/////////////////////////////////////////////////////////////////////////////
// CSeriesGroups properties

/////////////////////////////////////////////////////////////////////////////
// CSeriesGroups operations

CSeriesGroup CSeriesGroups::GetItems(long Index)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Index);
	return CSeriesGroup(pDispatch);
}

long CSeriesGroups::GetCount()
{
	long result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CSeriesGroups::Delete(long Index)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xd0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Index);
}

long CSeriesGroups::Contains(long SeriesIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		SeriesIndex);
	return result;
}

long CSeriesGroups::FindByName(LPCTSTR Name, BOOL CaseSensitive)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0xcc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Name, CaseSensitive);
	return result;
}
