// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "serieslist.h"

// Dispatch interfaces referenced by this interface
#include "SeriesGroups.h"


/////////////////////////////////////////////////////////////////////////////
// CSeriesList properties

/////////////////////////////////////////////////////////////////////////////
// CSeriesList operations

void CSeriesList::AddGroup(LPCTSTR Name)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Name);
}

BOOL CSeriesList::GetAllActive()
{
	BOOL result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CSeriesList::SetAllActive(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xca, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CSeriesGroups CSeriesList::GetGroups()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0xcb, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CSeriesGroups(pDispatch);
}

void CSeriesList::ClearValues()
{
	InvokeHelper(0xcc, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CSeriesList::First()
{
	long result;
	InvokeHelper(0xcd, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CSeriesList::Last()
{
	long result;
	InvokeHelper(0xce, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
