#if !defined(AFX_SHARPENFILTER_H__A739C11E_7F9F_425D_8CF7_151AABE73E50__INCLUDED_)
#define AFX_SHARPENFILTER_H__A739C11E_7F9F_425D_8CF7_151AABE73E50__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSharpenFilter wrapper class

class CSharpenFilter : public COleDispatchDriver
{
public:
	CSharpenFilter() {}		// Calls COleDispatchDriver default constructor
	CSharpenFilter(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSharpenFilter(const CSharpenFilter& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SHARPENFILTER_H__A739C11E_7F9F_425D_8CF7_151AABE73E50__INCLUDED_)
