#if !defined(AFX_SUBGRADIENT_H__324E0B54_ACC0_4B35_8CB6_B56D99C2FC22__INCLUDED_)
#define AFX_SUBGRADIENT_H__324E0B54_ACC0_4B35_8CB6_B56D99C2FC22__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSubGradient wrapper class

class CSubGradient : public COleDispatchDriver
{
public:
	CSubGradient() {}		// Calls COleDispatchDriver default constructor
	CSubGradient(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSubGradient(const CSubGradient& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetDirection();
	void SetDirection(long nNewValue);
	unsigned long GetStartColor();
	void SetStartColor(unsigned long newValue);
	unsigned long GetEndColor();
	void SetEndColor(unsigned long newValue);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	unsigned long GetMidColor();
	void SetMidColor(unsigned long newValue);
	long GetRadialX();
	void SetRadialX(long nNewValue);
	long GetRadialY();
	void SetRadialY(long nNewValue);
	long GetBalance();
	void SetBalance(long nNewValue);
	void ShowEditor(BOOL OnlyStartColor);
	long GetAngle();
	void SetAngle(long nNewValue);
	CSubGradient GetSubGradient();
	long GetTransparency();
	void SetTransparency(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SUBGRADIENT_H__324E0B54_ACC0_4B35_8CB6_B56D99C2FC22__INCLUDED_)
