#if !defined(AFX_SURFACESIDES1_H__B8352C06_83AA_4EB2_B642_2A0A5AE90DF9__INCLUDED_)
#define AFX_SURFACESIDES1_H__B8352C06_83AA_4EB2_B642_2A0A5AE90DF9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBrush1;
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CSurfaceSides wrapper class

class CSurfaceSides : public COleDispatchDriver
{
public:
	CSurfaceSides() {}		// Calls COleDispatchDriver default constructor
	CSurfaceSides(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSurfaceSides(const CSurfaceSides& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CBrush1 GetBrush();
	BOOL GetLevels();
	void SetLevels(BOOL bNewValue);
	CPen1 GetPen();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SURFACESIDES1_H__B8352C06_83AA_4EB2_B642_2A0A5AE90DF9__INCLUDED_)
