#if !defined(AFX_TEEOPENGL_H__F639438A_0D58_4498_BA63_5E8E2DC22C98__INCLUDED_)
#define AFX_TEEOPENGL_H__F639438A_0D58_4498_BA63_5E8E2DC22C98__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeePoint3D;
class CGLLightSource;

/////////////////////////////////////////////////////////////////////////////
// CTeeOpenGL wrapper class

class CTeeOpenGL : public COleDispatchDriver
{
public:
	CTeeOpenGL() {}		// Calls COleDispatchDriver default constructor
	CTeeOpenGL(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeOpenGL(const CTeeOpenGL& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetActive();
	void SetActive(BOOL bNewValue);
	long GetAmbientLight();
	void SetAmbientLight(long nNewValue);
	CTeePoint3D GetLightPosition();
	unsigned long GetLightColor();
	void SetLightColor(unsigned long newValue);
	BOOL GetFontOutlines();
	void SetFontOutlines(BOOL bNewValue);
	BOOL GetShadeQuality();
	void SetShadeQuality(BOOL bNewValue);
	BOOL GetAntialias();
	void SetAntialias(BOOL bNewValue);
	long GetFontExtrusion();
	void SetFontExtrusion(long nNewValue);
	CGLLightSource GetLight();
	CGLLightSource GetLight1();
	CGLLightSource GetLight2();
	double GetShininess();
	void SetShininess(double newValue);
	void ShowEditor();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEEOPENGL_H__F639438A_0D58_4498_BA63_5E8E2DC22C98__INCLUDED_)
