#if !defined(AFX_TEESHAPE_H__858D6485_03FD_4E5F_8182_67EED75F27AE__INCLUDED_)
#define AFX_TEESHAPE_H__858D6485_03FD_4E5F_8182_67EED75F27AE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CGradient;
class CChartFont;
class CTeeShadow;

/////////////////////////////////////////////////////////////////////////////
// CTeeShape wrapper class

class CTeeShape : public COleDispatchDriver
{
public:
	CTeeShape() {}		// Calls COleDispatchDriver default constructor
	CTeeShape(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeShape(const CTeeShape& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetTransparency();
	void SetTransparency(long nNewValue);
	long GetBevel();
	void SetBevel(long nNewValue);
	long GetBevelWidth();
	void SetBevelWidth(long nNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
	CGradient GetGradient();
	CChartFont GetFont();
	CTeeShadow GetShadow();
	long GetShapeStyle();
	void SetShapeStyle(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TEESHAPE_H__858D6485_03FD_4E5F_8182_67EED75F27AE__INCLUDED_)
