// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "transposeseriestool.h"


/////////////////////////////////////////////////////////////////////////////
// CTransposeSeriesTool properties

/////////////////////////////////////////////////////////////////////////////
// CTransposeSeriesTool operations

void CTransposeSeriesTool::Transpose()
{
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
